name: Github Pages
on:
  push:
    branches:
      - master
env:
  MAINNET_API_KEY: ${{secrets.MAINNET_API_KEY}}
  KOVAN_API_KEY: ${{secrets.KOVAN_API_KEY}}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install and Build
        run: yarn install
      - name: Build Expo Web
        run: expo build:web
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: web-build
